version: '2'

services:
  db:
    container_name: phone_book_db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - ./db:/root/db

  web:
    container_name: phone_book_web
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - ~/.m2:/root/.m2

    tty: true
    stdin_open: true
